- client/package.json
- client/yarn.lock
> setup: webpack-cli 버전 및 command 변경

- server/.env.defaults
- server/package.json
- server/src/app.ts
- server/src/databases/index.ts
- server/yarn.lock
typeorm 셋업
- .env 파일은 git으로 공개되면 안됩니다. (그래서 .env.defaults 만 포함되어 있습니다.)
- .env 내용은 Notion으로 공유할게요.
> Setup typeorm

- client/src/controller/controller.ts
- client/src/controller/main.ts
- client/src/core/jsx.ts
- client/src/index.ts
- client/src/store/menu.ts
- client/src/store/store.ts
- client/src/store/user.ts
- client/src/utils.ts
- client/src/view/components/component.ts
- client/src/view/components/userinfo.comp.ts
- client/src/view/main.ts
- client/src/view/pages/main.ts
- client/src/view/pages/page.ts
- client/src/view/view.ts
프론트엔드 MVC Architecture 도입
- god 인규님의 jsx.ts 사용!
- 다만, 아직 checked 같은 속성을 부여하는것이 좀 어렵다.
> Setup fe mvc arch

- client/src/core/router.ts
- client/src/index.ts
- client/src/view/customElements/router-link.ts
- client/src/view/pages/login.ts
- client/src/view/pages/main.ts
- client/webpack.dev.js
라우터 설정 추가
- <router-link to="주소">글자</router-link> 로 사용할수 있습니다.
> Setup router

- client/package.json
- client/src/view/pages/login.ts
- client/webpack.dev.js
- server/DTO/githubLogin.ts
- server/package.json
- server/src/app.ts
- server/src/index.ts
- server/src/routes/githubLogin.ts
- server/src/routes/user.ts
- server/yarn.lock
깃허브 소셜 로그인 추가
-  하프 페어코딩함.
- 나중에 config들 밖으로 빼놔야함.
> Feat GitHub login

- server/src/app.ts
- server/src/entity/paymentCategory.entity.ts
- server/src/entity/paymentHistory.entity.ts
- server/src/entity/paymentMethod.entity.ts
payment_method 테이블에 id 칼럼 추가
- 페어코딩으로 @cothis 님과 진행함
> fix: 결제수단 id 칼럼 추가

- client/src/core/router.ts
router의 메소드를 좀더 정리해봤습니다.
> 0.5 mh
> refactor: router.ts

- client/src/view/pages/login.ts
- server/src/routes/githubLogin.ts
fix: 배포판과 localhost 구분
- 이제 로컬환경에서는 server/.env 설정이 1라인 추가됩니다.
```sh
self_url=http://localhost:3000
```
> 20 mm
> fix: 배포판과 localhost 구분

- .vscode/settings.json
- client/src/core/router.ts
- server/src/app.ts
- server/src/controllers/GithubController.ts
- server/src/controllers/UserController.ts
- server/src/routes/githubLogin.ts
- server/src/routes/router.ts
- server/src/routes/user.ts
기존 라우터를  라우터와 컨트롤러로 분리했습니다.
> 1 mh
resolve #33
> feat: router, controller 분리

- .gitignore
> chore: ignore tailwind.css

- client/src/view/pages/login.ts
- server/.env.defaults
- server/src/app.ts
- server/src/errors/ErrorController.ts
- server/src/errors/customErrors.ts
- server/src/middlewares/auth.ts
- server/src/routes/router.ts
- server/src/services/CategoryService.spec.ts
- server/src/services/MethodService.spec.ts
에러핸들러 및 미들웨어 개발 했습니다.
로그인페이지에서 테스트하는 부분도 변경했습니다.
- CategoryService, MethodService 간단한 유닛테스트 추가
> 1 mh
resolve #44
> Feat middlewares

- pages/styles/calendar.css
> style: 캘린더 셀 색상 변경

- client/src/index.ts
- client/src/view/customElements/app-header.ts
- client/src/view/customElements/list-item.ts
- client/src/view/customElements/list-title.ts
- client/src/view/pages/list.ts
- server/src/app.ts
List page 관련 컴포넌트 작성
- jsx 속성없는 조건식 추후 적용예정
- database 연동은 이후 풀리퀘에서 진행할게요
> 3 mh
> Feat list page 관련 컴포넌트 작성

- client/src/controller/history.ts
- client/src/index.ts
- client/src/store/history.ts
- client/src/types/index.ts
- client/src/utils.ts
- client/src/view/pages/list.ts
- client/src/view/pages/login.ts
- server/src/services/HistoryService.ts
history data 백엔드 연동
- (특이 사항 1)
- (특이 사항 2)
- (특이 사항 3)
> N mh
> Feat list link

- client/src/core/router.ts
- client/src/index.ts
router.setDefaultPage(loginPage) 추가하여 route시 경로가 없으면 default로 이동
> 0.1 mh
> feat: router default page 기능 추가

- client/package.json
- client/src/DTO/category.ts
- client/src/DTO/history.ts
- client/src/DTO/method.ts
- client/src/api/histories.ts
- client/src/controller/history.ts
- client/src/core/router.ts
- client/src/index.ts
- client/src/types/index.ts
- client/src/view/customElements/calendar-cell.ts
- client/src/view/pages/calendar.ts
- client/src/view/pages/page.ts
- client/src/view/styles/calendar.css
- client/yarn.lock
페이지 라우터가 페이지 객체맵을 갖고있는것이 아닌 페이지 생성자 맵을 갖고있도록 변경.
DTO 추가, 프론트단에서 API 추가
> 1 mh
> Fix page router

- client/src/api/apis.ts
- client/src/controller/controller.ts
- client/src/controller/history.ts
- client/src/store/history.ts
- client/src/utils.ts
- client/src/view/customElements/category-select.ts
- client/src/view/customElements/history-form.ts
- client/src/view/customElements/history-list.ts
- client/src/view/customElements/index.ts
- client/src/view/customElements/method-select.ts
- client/src/view/customElements/pay-type.ts
- client/src/view/pages/list.ts
- client/src/view/pages/login.ts
- server/src/controllers/HistoryController.ts
- server/src/services/HistoryService.ts
create 기능 및 입금, 출금 선택기능 개발
- (특이 사항 1)
- (특이 사항 2)
- (특이 사항 3)
> 3 mh
> Feat list create 및 입금 출금 필터링

- client/src/types/index.ts
- server/src/controllers/MethodController.ts
- server/src/entity/paymentMethod.entity.ts
- server/src/services/CategoryService.ts
- server/src/services/MethodService.ts
(작업 내역 한줄로 요약)
(작업 내역 확인하기 편하도록 gif 첨부)
- (특이 사항 1)
- (특이 사항 2)
- (특이 사항 3)
> N mh
> fix: method githubid 제거

- server/src/controllers/HistoryController.ts
- server/src/routes/history.ts
- server/src/services/HistoryService.ts
/api/histories/apply 주소로 아래와 같은 데이터를 입력하여 처리할 수 있습니다.
``` json
[
{
"uuid": 1,
"content": "Test",
"amount": 3000
},
{
"content": "newData",
"amount": 3000,
"isIncome": true,
"methodId": 1,
"payDate": "2021-08-03",
"categoryName": "문화/여가"
}
]    
```
> 0.5 mh
> feat: applychanges 추가

- server/src/DTO/HistoryApplyDto.ts
- server/src/controllers/HistoryController.ts
- server/src/controllers/MethodController.ts
- server/src/entity/paymentHistory.entity.ts
- server/src/routes/router.ts
- server/src/services/MethodService.spec.ts
- server/src/services/MethodService.ts
메소드 수정 및 apply 파라미터 methodName으로 변경
history apply dto 생성
- 포스트맨 테스트 완료
> 1 mh
> feat: 메소드 수정 및 apply 파라미터 methodName으로 변경

- client/src/view/customElements/history-form.ts
- client/src/view/pages/list.ts
list page 의 day, month 를 기본적으로 오늘 기준으로 수정했습니다.
- 이전달, 다음달에 따라 month 를 바꾸는 로직이 필요합니다.
> 10 mm
> feat: default day, month 수정

- client/src/index.ts
- client/src/view/components/Component.ts
- client/src/view/components/UserInfo.ts
- client/src/view/pages/main.ts
- server/src/middlewares/auth.ts
- server/src/routes/history.ts
- server/src/services/HistoryService.ts
우분투에서 대소문자 fix하고 빌드가 되는것을 확인했습니다.
> fix: case sensitive issue
